server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root123@
    url: jdbc:mysql://49.235.235.143:3306/demo-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai